
name: CI-CD Pipeline

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Clone
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install -y nginx
          npm install

      - name: Run Tests
        run: npm test

  Deploy:
    runs-on: ubuntu-latest
    needs: Test

    steps:
      - name: SSH Command
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            pwd