name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Clone
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install -y nginx
          npm install

      - name: Run Tests
        run: npm run test > test.txt
      
      - name: upload artifact
        uses : actions/upload-artifact@v4
        with:
         name: test-result
         path : ./test.txt


  Deploy:
    runs-on: self-hosted
    needs: Test

    steps:
      - name: Create A Folder
        run: |
          cd ~
          pwd
          mkdir -p dipto
          cd dipto
          touch hello.txt
          echo "hello world ok" > hello.txt
          ls -la

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
         name: test.txt
      - name : Display articaft  
        run: |
         ls -l 
         cat test.txt 